/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as HoroscopeIndexRouteImport } from './routes/horoscope/index'
import { Route as ReadingIndexRouteImport } from './routes/reading/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopeIndexRoute = HoroscopeIndexRouteImport.update({
  id: '/horoscope/',
  path: '/horoscope/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingIndexRoute = ReadingIndexRouteImport.update({
  id: '/reading/',
  path: '/reading/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/': typeof AdminIndexRoute
  '/horoscope/': typeof HoroscopeIndexRoute
  '/reading/': typeof ReadingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminIndexRoute
  '/horoscope': typeof HoroscopeIndexRoute
  '/reading': typeof ReadingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/': typeof AdminIndexRoute
  '/horoscope/': typeof HoroscopeIndexRoute
  '/reading/': typeof ReadingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/admin/' | '/horoscope/' | '/reading/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/admin' | '/horoscope' | '/reading'
  id: '__root__' | '/' | '/about' | '/admin/' | '/horoscope/' | '/reading/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminIndexRoute: typeof AdminIndexRoute
  HoroscopeIndexRoute: typeof HoroscopeIndexRoute
  ReadingIndexRoute: typeof ReadingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscope/': {
      id: '/horoscope/'
      path: '/horoscope'
      fullPath: '/horoscope/'
      preLoaderRoute: typeof HoroscopeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading/': {
      id: '/reading/'
      path: '/reading'
      fullPath: '/reading/'
      preLoaderRoute: typeof ReadingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminIndexRoute: AdminIndexRoute,
  HoroscopeIndexRoute: HoroscopeIndexRoute,
  ReadingIndexRoute: ReadingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
